#include <QtWidgets>
#include <Windows.h>
#include <spdlog/tweakme.h>
#include <iostream>
#include <Windows.h>
#include <conio.h>
#include <spdlog/spdlog.h>
#include <fmt/xchar.h>
#include <fmt/color.h>
#include <chrono>
#include <fstream>
#include <filesystem>
#include <future>
#include <bitset>
#include <QtCharts>
#include <spdlog/sinks/basic_file_sink.h>
#include <QMessageBox>
#include <QPixMap>
//#include <boost/serialization/map.hpp>
//#include <boost/serialization/array.hpp>
//#include <boost/serialization/list.hpp>
//#include <boost/serialization/vector.hpp>
//#include <boost/serialization/serialization.hpp>
//#include <boost/archive/text_oarchive.hpp>
//#include <boost/archive/text_iarchive.hpp>
//#include <cryptopp/aes.h>
//#include <cryptopp/eccrypto.h>
//#include <cryptopp/osrng.h>
//#include <cryptopp/oids.h>
//#include <cryptopp/hex.h>
//#include <cryptopp/filters.h>
//#include <cryptopp/modes.h>
//#include <cryptopp/files.h>
//#include <clipboardxx.hpp>
//#include <lazy_importer.hpp>